name: Givme Test

"on":
  push: {}
  workflow_dispatch: {}

jobs:
  test:
    name: Test Givme
    runs-on: ubuntu-latest
    container: ghcr.io/kukaryambik/givme:latest
    steps:
      - name: Givme run
        run: givme run curlimages/curl -- --version

      - name: Givme apply & snapshot
        run: |-
          eval $(givme apply ubuntu)
          apt-get update && apt-get install -y fortune cowsay
          /usr/games/fortune | /usr/games/cowsay
          export SNAP=$(givme snapshot)
          echo "SNAP=$SNAP" >> $GITHUB_ENV

      - name: Givme exec
        run: givme exec alpine/helm version

      - name: Givme getenv
        run: |-
          eval $(givme getenv alpine/helm)
          helm version

      - name: Givme purge & extract
        run: |-
          givme purge
          ls -l /
          givme extract ${{ env.SNAP }}
          . <(givme env ${{ env.SNAP }})
          ls -l /
          apt-get --help
