name: Givme Test

"on":
  push: {}
  workflow_dispatch: {}

jobs:
  test:
    name: Test Givme
    runs-on: ubuntu-latest
    container: ghcr.io/kukaryambik/givme:v1.5.7
    steps:
      - name: Givme run
        run: givme run curlimages/curl -- --version

      - name: Givme apply
        run: |-
          eval $(givme apply ubuntu)
          apt-get update && apt-get install -y fortune cowsay
          /usr/games/fortune | /usr/games/cowsay

      - name: Givme snapshot
        run: |-
          export SNAP=$(givme snapshot)
          echo "Snapshot created: $SNAP"

      - name: Givme exec
        run: givme exec alpine/helm version

      - name: Givme getenv
        run: |-
          eval $(givme getenv alpine/helm)
          helm version

      - name: Givme purge & extract
        run: |-
          /givme/givme purge
          /givme/bin/ls -l /
          /givme/givme extract $SNAP
          /givme/givme env $SNAP
          ls -l /
          apt-get --help
